// ESR DEVELOPERS - PLOT INVENTORY DATASET
export const INITIAL_PLOTS = [
  {
    id: "plot-101",
    number: "101",
    phase: "Phase 1 - Royal Enclave",
    sqYards: 200,
    dimensions: "36' x 50'",
    facing: "East Facing",
    pricePerSqYd: 12500,
    status: "available",
    roadWidth: "40 Feet Road",
    tokenAmount: 50000,
    isCorner: false
  },
  {
    id: "plot-102",
    number: "102",
    phase: "Phase 1 - Royal Enclave",
    sqYards: 200,
    dimensions: "36' x 50'",
    facing: "East Facing",
    pricePerSqYd: 12500,
    status: "available",
    roadWidth: "40 Feet Road",
    tokenAmount: 50000,
    isCorner: false
  },
  {
    id: "plot-103",
    number: "103",
    phase: "Phase 1 - Royal Enclave",
    sqYards: 267,
    dimensions: "40' x 60'",
    facing: "North-East",
    pricePerSqYd: 13500,
    status: "available",
    roadWidth: "60 Feet Main Road",
    tokenAmount: 75000,
    isCorner: true
  },
  {
    id: "plot-104",
    number: "104",
    phase: "Phase 1 - Royal Enclave",
    sqYards: 200,
    dimensions: "36' x 50'",
    facing: "East Facing",
    pricePerSqYd: 12500,
    status: "available",
    roadWidth: "40 Feet Road",
    tokenAmount: 50000,
    isCorner: false
  },
  {
    id: "plot-105",
    number: "105",
    phase: "Phase 1 - Royal Enclave",
    sqYards: 200,
    dimensions: "36' x 50'",
    facing: "West Facing",
    pricePerSqYd: 12000,
    status: "booked",
    roadWidth: "40 Feet Road",
    tokenAmount: 50000,
    bookedBy: "Ramesh Reddy (Hyd)",
    isCorner: false
  },
  {
    id: "plot-106",
    number: "106",
    phase: "Phase 1 - Royal Enclave",
    sqYards: 300,
    dimensions: "45' x 60'",
    facing: "East Facing",
    pricePerSqYd: 13000,
    status: "available",
    roadWidth: "40 Feet Road",
    tokenAmount: 75000,
    isCorner: false
  },
  {
    id: "plot-107",
    number: "107",
    phase: "Phase 1 - Royal Enclave",
    sqYards: 267,
    dimensions: "40' x 60'",
    facing: "South-East",
    pricePerSqYd: 13000,
    status: "sold",
    roadWidth: "40 Feet Road",
    tokenAmount: 75000,
    isCorner: true
  },
  {
    id: "plot-108",
    number: "108",
    phase: "Phase 1 - Royal Enclave",
    sqYards: 200,
    dimensions: "36' x 50'",
    facing: "West Facing",
    pricePerSqYd: 12000,
    status: "available",
    roadWidth: "40 Feet Road",
    tokenAmount: 50000,
    isCorner: false
  },
  {
    id: "plot-109",
    number: "109",
    phase: "Phase 2 - Gold Coast",
    sqYards: 180,
    dimensions: "30' x 54'",
    facing: "East Facing",
    pricePerSqYd: 12200,
    status: "available",
    roadWidth: "30 Feet Road",
    tokenAmount: 50000,
    isCorner: false
  },
  {
    id: "plot-110",
    number: "110",
    phase: "Phase 2 - Gold Coast",
    sqYards: 180,
    dimensions: "30' x 54'",
    facing: "East Facing",
    pricePerSqYd: 12200,
    status: "available",
    roadWidth: "30 Feet Road",
    tokenAmount: 50000,
    isCorner: false
  },
  {
    id: "plot-111",
    number: "111",
    phase: "Phase 2 - Gold Coast",
    sqYards: 240,
    dimensions: "36' x 60'",
    facing: "North-East",
    pricePerSqYd: 13200,
    status: "available",
    roadWidth: "40 Feet Road",
    tokenAmount: 60000,
    isCorner: true
  },
  {
    id: "plot-112",
    number: "112",
    phase: "Phase 2 - Gold Coast",
    sqYards: 200,
    dimensions: "36' x 50'",
    facing: "East Facing",
    pricePerSqYd: 12500,
    status: "booked",
    roadWidth: "40 Feet Road",
    tokenAmount: 50000,
    bookedBy: "Srinivas Rao (Vijayawada)",
    isCorner: false
  },
  {
    id: "plot-113",
    number: "113",
    phase: "Phase 2 - Gold Coast",
    sqYards: 200,
    dimensions: "36' x 50'",
    facing: "West Facing",
    pricePerSqYd: 12000,
    status: "available",
    roadWidth: "40 Feet Road",
    tokenAmount: 50000,
    isCorner: false
  },
  {
    id: "plot-114",
    number: "114",
    phase: "Phase 2 - Gold Coast",
    sqYards: 333,
    dimensions: "50' x 60'",
    facing: "East Facing",
    pricePerSqYd: 13500,
    status: "available",
    roadWidth: "60 Feet Main Road",
    tokenAmount: 100000,
    isCorner: false
  },
  {
    id: "plot-115",
    number: "115",
    phase: "Phase 3 - Paradise Park",
    sqYards: 500,
    dimensions: "60' x 75'",
    facing: "North-East",
    pricePerSqYd: 14000,
    status: "available",
    roadWidth: "60 Feet Commercial Road",
    tokenAmount: 150000,
    isCorner: true
  },
  {
    id: "plot-116",
    number: "116",
    phase: "Phase 3 - Paradise Park",
    sqYards: 250,
    dimensions: "37.5' x 60'",
    facing: "East Facing",
    pricePerSqYd: 12800,
    status: "available",
    roadWidth: "40 Feet Road",
    tokenAmount: 60000,
    isCorner: false
  }
];
